# DAY 1 ( 30_Aug )

In [1]:
7+10

17

In [2]:
print(7+10)

17


- **Exponentiation** **
- **Modulo** %

In [3]:
print(100 * (1.1 ** 7))
print(104 % 3)

194.87171000000012
2


- **Variables**

In [4]:
savings = 100
print(savings)

100


In [5]:
# Create a variable savings
savings = 100

# Create a variable growth_multiplier
growth_multiplier = 1.1

# Calculate result
result = (100 * (growth_multiplier ** 7))

# Print out result
print(result)

194.87171000000012


- Data types (**string** & **boolean**)

In [9]:
# Create a variable desc
desc = "compound interest"

# Create a variable profitable
profitable = True

print(desc)
print(profitable)

compound interest
True


In [10]:
a = 94.2356
b = "Shahwar Alam Naqvi"
c = False

In [11]:
type(a)

float

In [12]:
type(b)

str

In [13]:
type(c)

bool

In [14]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

# Assign product of growth_multiplier and savings to year1
year1 = savings * growth_multiplier

# Print the type of year1
print(type(year1))

# Assign sum of desc and desc to doubledesc
doubledesc = desc + desc
print(doubledesc)

<class 'float'>
compound interestcompound interest


- **Type conversion**

In [17]:
# Definition of savings and result
savings = 100
result = 100 * 1.10 ** 7

# Fix the printout
print("I started with $" + str(savings) + " and now have $" + str(result) + ". Awesome!")

# Definition of pi_string
pi_string = "3.1415926"

# Convert pi_string into float: pi_float
pi_float = float(pi_string)
print(pi_string,"this is string")
print(pi_float,"this is float")

I started with $100 and now have $194.87171000000012. Awesome!
3.1415926 this is string
3.1415926 this is float


In [18]:
1 + 1

2

In [19]:
True + True

2

In [20]:
1 + 0

1

In [21]:
True + False

1

In [22]:
5 * True - 6 * True 

-1

In [1]:
z = 1
bool(z)

True

In [2]:
z = 23
bool(z)

True

In [3]:
z = 0
bool(z)

False

In [4]:
z = -25    #strange (apart from 0 rest all are true)
bool(z)

True

- **Lists**(compound data type)

In [23]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall , kit , liv , bed , bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [24]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ["hallway" , hall ,"kitchen" , kit , "living room", liv, "bedroom" , bed, "bathroom", bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


_List itself is also a Python type. That means that a list can also contain a list!_

In [25]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom",bed],
         ["bathroom",bath]]
# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


In [26]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

11.25
9.5
20.0


In [28]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Sum of kitchen and bedroom area: eat_sleep_area
eat_sleep_area = areas[3] + areas[7]

# Print the variable eat_sleep_area
print(eat_sleep_area)

28.75


In [29]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[6:]

# Print out downstairs and upstairs
print(downstairs)
print(upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]


- **Subsetting**(narrowing down)

In [30]:
x = [["a", "b", "c"],
     ["d", "e", "f"],
     ["g", "h", "i"]]
x[2][0]

'g'

- **List manipulation**

In [32]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Correct the bathroom area
areas[9] = 10.50

# Change "living room" to "chill zone"
areas[4] = "chill zone"

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5]


In [33]:
x = ["a", "b", "c", "d"]
y = x + ["e", "f"]

y

['a', 'b', 'c', 'd', 'e', 'f']

In [34]:
# Create the areas list and make some changes
areas = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0,
         "bedroom", 10.75, "bathroom", 10.50]

# Add poolhouse data to areas, new list is areas_1

areas_1 = areas + ["poolhouse", 24.5]

# Add garage data to areas_1, new list is areas_2

areas_2 = areas_1 + ["garage",15.45]

print(areas_2)


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]


In [36]:
#deleting
x = ["a", "b", "c", "d"]
del(x[1])

x

['a', 'c', 'd']

_The ; sign is used to place commands on the same line._

In [37]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

- **Implicit copy**_(original list gets affected)_

In [44]:
# Create list areas
x = [11.25, 18.0, 20.0, 10.75, 9.50]

# Create y
y = x        #reference of the list is copied not the actual list , but if you make changes to y x changes too

# Change y
y[0] = 5.0

# Print x
print(x)
print(y)

# same , both x&y this is because x and y point to same list (very important)

print('\n')

del(x[0])

print(x)
print(y)      #again affect on both



[5.0, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


[18.0, 20.0, 10.75, 9.5]
[18.0, 20.0, 10.75, 9.5]


- **Explicit copy**_(original list does not get affected)_

In [47]:
x = [11.25, 18.0, 20.0, 10.75, 9.50]

# now to create y such that it doesnot refer to x list and refers to actually new list , only values of x are copied.

y = list(x) # or y=x[:]

# now let us change and see the effect on both

y[0] = 5.0

print(x)
print(y)

#....hurray...!!!

[11.25, 18.0, 20.0, 10.75, 9.5]
[5.0, 18.0, 20.0, 10.75, 9.5]


_The difference between explicit and reference-based copies is subtle, but can be really important. Try to keep in mind how a list is stored in the computer's memory_

# DAY 2 ( 31_Aug )

- **Function**(reusable code)

some buit-in functions

In [5]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)
print(out2)

<class 'list'>
4
1


help :

In [6]:
?max  # for knowing the docstring

# square backet for the argument means that the argument is optional.

sorted func : 

In [7]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full , key=None ,reverse = True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


- **Methods**

In Python **Everything = Object** and each _object_ has set of _methods_ associated with them.

or

Methods are specific functions that are associated with Python Objects

Eg - str , lists , int etc are objects.

Methods associated with eg. lists are _list.index("blabla")_ , _list.count(1.73) etc...._

In [8]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count('o'))

poolhouse
POOLHOUSE
3


In [9]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Print out the index of the element 20.0
print(areas.index(20.0))

# Print out how often 9.50 appears in areas
print(areas.count(9.50))

2
1


In [11]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


- **PACKAGES**

Packages = Python scripts

Each python script = module

Each module = functions ,methods and types

Eg of some packages : Numpy , Matplotlib , Scikit-Learn etc..

--importing

In [12]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2*math.pi*r

# Calculate A
A = math.pi*(r**2)

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


--selective importing

In [13]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
dist = r * radians(12)

# Print out dist
print(dist)

40317.10572106901


In [14]:
from scipy.linalg import inv as my_inv

my_inv([[1,2], [3,4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

- **NUMPY**

Numpy = Numeric Python

Alternatie to Python list  :_Numpy Array_

Numpy array is similar to lists but with additional features eg.

            calculations over entire array
            easy
            fast

Numpy array will have only one type inside , if you give more than one type , they will be converted to one type itself

watch this cell below ... see the difference while we add list + list and array + array.

In [17]:
import numpy as np

In [18]:
list_1 = [1,2,3]
list_2 = [4,5,6]

list_1 + list_2             # gets combined

[1, 2, 3, 4, 5, 6]

In [20]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

array_1 + array_2           # additin happens 

array([5, 7, 9])

In [21]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


In [24]:
# height_in is a regular list
height_in = [74 , 74 , 72 , 75 , 75 , 73]

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

[74 74 72 75 75 73]
[1.8796 1.8796 1.8288 1.905  1.905  1.8542]


In [2]:
# height and weight are regular lists
height_in = [74,74,72,75,75,73]
weight_lb = [84,56,45,67,104,45]

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / (np_height_m ** 2)

# Print out bmi
print(bmi)

[10.78484231  7.18989488  6.10302957  8.37433305 12.99896474  5.93696853]


In [3]:
x = [4 , 9 , 6, 3, 1]

import numpy as np
y = np.array(x)

y

array([4, 9, 6, 3, 1])

In [4]:
y[y>5]   # quite like selection isn't it

array([9, 6])

In [5]:
new_arr = np.array(y>5)     # this creates arr of bool values , see there is True where 9 and 6 , bcz they are > 5

new_arr               

array([False,  True,  True, False, False])

In [6]:
# more of previously mentioned concept

# height and weight are available as a regular lists

height_in = [74,74,72,75,75,73]
weight_lb = [84,56,45,67,104,45]

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = np.array(bmi < 21)

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[bmi < 21])


[ True  True  True  True  True  True]
[10.78484231  7.18989488  6.10302957  8.37433305 12.99896474  5.93696853]


# DAY 3 (1 Sept)

Type Coercion is the conversion of one type of object to a new object of a different type with similar content.

First of all, numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as type coercion.

Second, the typical arithmetic operators, such as +, -, * and / have a different meaning for regular Python lists and numpy arrays.

In [7]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

let's see a bit of subsetting

In [8]:
x = ["a", "b", "c"]
x[1]

np_x = np.array(x)
np_x[1]

'b'

In [12]:
# Import numpy
import numpy as np

height_in = [74,74,72,75,75,73]
weight_lb = [84,56,45,67,104,45]

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 4
print(np_weight_lb[4])

# Print out sub-array of np_height_in: index 3 up to and including index 6
print(np_height_in[2:7])

104
[72 75 75 73]


In [13]:
type(np_weight_lb)

numpy.ndarray

here numpy is the package and "ndarray" is n dimensional array.

- **2D Numpy Arrays**

In [14]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))


# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


In [20]:
# baseball 
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


# Import numpy package
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


In [18]:
# regular list of lists
x = [["a", "b"], ["c", "d"]]
[x[0][0], x[1][0]]       # view with focus here

# numpy
import numpy as np
np_x = np.array(x)
np_x[:,0]

array(['a', 'c'], dtype='<U1')

 The indexes before the comma refer to the rows, while those after the comma refer to the columns.
 
 The : is for slicing
 
 Here , 
 
 The first column contains the players' height in inches and the second column holds player weight, in pounds

In [26]:
# baseball 
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


# Import numpy package
import numpy as np

# Create np_baseball (2 cols)
np_baseball = np.array(baseball)
print(np_baseball)

print('\n')

# Print out the 4th row of np_baseball
print(np_baseball[3,:])

print('\n')

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]

# Print out height of 2nd player
print(np_baseball[1:2 ,0])

[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]


[188.   75.2]


[215.]


2D Arithmetic

In [28]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
np_mat * 2
np_mat + np.array([10, 10])
np_mat + np_mat

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

# DAY 4 ( 2 Sept )

In [17]:
# baseball is available as a regular list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]


# updated is available as 2D numpy array
update_list = [[  -80 , -8.4],
               [  -15 , -2.7],
               [  -10 , -8.5],
               [  -8  , -5.2]]


# Import numpy package
import numpy as np

# Create np_baseball 
np_baseball = np.array(baseball)

#create updated array
updated = np.array(update_list)

# Print out addition of np_baseball and updated
print(np_baseball + updated)

# Create numpy array: conversion
conversion = np.array([[0.0254 , 0.453592 , 1],
                      [0.0254 , 0.453592 , 1]])

print('\n')
print(np_baseball.shape)
print(conversion.shape)
print('\n')

# Print out product of np_baseball and conversion
print(np.dot(np_baseball,conversion))      # * creates problem in matrix multiplication , therefor use : .dot().
print('\n')
print(np.dot(np_baseball,conversion).shape)

[[100.  70.]
 [200. 100.]
 [200.  90.]
 [180.  70.]]


(4, 2)
(2, 3)


[[  6.56336   117.2081728 258.4      ]
 [  8.06958   144.1061784 317.7      ]
 [  7.8359    139.933132  308.5      ]
 [  6.68528   119.3854144 263.2      ]]


(4, 3)


Notice how with very little code, you can change all values in your numpy data structure in a very specific way. This will be very useful in your future as a data scientist!

- **Numpy : Basic Statistics**

mean , median

In [19]:
import numpy as np
x = [1, 4, 8, 10, 12]
print(np.mean(x))
np.median((x))

7.0


8.0

In [20]:
# np_baseball is available

# Import numpy
import numpy as np

# Create np_height_in from np_baseball
np_height_in = np_baseball[:,0]

# Print out the mean of np_height_in
print(np.mean(np_height_in))

# Print out the median of np_height_in
print(np.median(np_height_in))

198.25
199.0


 It's always a good idea to check both the median and the mean, to get an idea about the overall distribution of the entire dataset.

In [21]:
# np_baseball is available

# Import numpy
import numpy as np

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height.
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. 
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column.
corr = np.corrcoef(np_baseball[:,0] , np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]


**Numpy final exercise**

You've contacted FIFA for some data and they handed you two lists. The lists are the following:

positions = ['GK', 'M', 'A', 'D', ...]
heights = [191, 184, 185, 180, ...]
Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

In [26]:
# heights and positions are available as lists
positions = ['GK',
 'M',
 'A',
 'D',
 'M',
 'GK',
 'M',
 'D',
 'A',
 'D',
 'M',
 'M',
 'D',
 'M',
 'GK',
 'D']


heights = [191,
 184,
 185,
 180,
 181,
 187,
 170,
 179,
 183,
 186,
 185,
 170,
 187,
 183,
 173,
 188]



# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of goalkeepers: 187.0
Median height of other players: 183.0
